BaseURL = "https://dimorng.github.io/"
languageCode = "en-us"
title = "Dr. Dimorng MEUNG (DDS)"
theme = "googoraa-hugo-theme"
paginate = 20
disqusShortname = "googoraa"

[markup.goldmark.renderer]
    unsafe= true

[params]
    description = "Dentistry and More"
    gravatar = "a88521b4b3cfb44adb230231069de77d"
    # Google Analytics 4
    googleAnalyticsID = "G-GR2RY1GHZE"